name: chopwell_rider_application
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+11

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  badges: ^2.0.3
  intl: ^0.17.0
  flutter_vector_icons: ^2.0.0
  persistent_bottom_nav_bar_v2: ^4.2.5
  flutter_riverpod: ^1.0.3+1
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  jiffy: ^5.0.0
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  shared_preferences_riverpod: ^0.2.0
  cached_network_image: ^3.2.2
  image_picker: ^0.8.6
  another_flushbar: ^1.12.29
  animated_splash_screen: ^1.3.0
  permission_handler: ^10.0.0
  shimmer: ^2.0.0
  geolocator: ^9.0.2
  pin_code_fields: ^7.4.0
  flutter_svg: ^2.0.2
  sliding_sheet: ^0.5.2
  firebase_core: ^2.7.0
  onesignal_flutter: ^3.5.0
  google_maps_flutter: ^2.2.5
  url_launcher: ^6.1.10
  maps_places_autocomplete: ^0.0.2
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_imagekit: ^0.0.5
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.2.19
  flutter_dotenv: ^5.0.2
  jwt_decoder: ^2.0.1
  flutter_phone_direct_caller: ^2.1.1
  alarm: ^1.1.4
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.4
  json_serializable: ^6.6.1
  freezed: ^2.1.1
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "EC0606"
  image: assets/chopwell_icon.svg

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          style: normal

    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
