name: chopwell_merchant_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1
  drop_shadow_image: ^0.9.1
  flutter_native_splash: ^2.2.16
  sliding_sheet: ^0.5.2
  provider: ^6.0.5


  dependencies:
  flutter_app_badger: ^1.5.0
  faker: ^2.1.0
  badges: ^2.0.3
  persistent_bottom_nav_bar_v2: ^4.2.5
  flutter_bloc: ^8.1.1
  web_socket_channel: ^2.1.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  shared_preferences_riverpod: ^0.2.0
  cached_network_image: ^3.2.2
  image_picker: ^0.8.6
  flutter_riverpod: ^1.0.4
  dio: ^4.0.6
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  animated_splash_screen: ^1.3.0
  socket_io_client: ^2.0.0
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  geolocator: ^9.0.2
  image_cropper: ^3.0.1
  another_flushbar: ^1.12.29
  pinput: ^2.2.16
  equatable: ^2.0.5
  jiffy: ^5.0.0
  shimmer: ^2.0.0
  intl: ^0.17.0
  open_mail_app: ^0.4.5
  flutter_vector_icons: ^2.0.0










dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "EC0606"
  image: assets/chopwell_icon.svg

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/
    - assets/



  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          style: normal

    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf


