name: chopwell_rider_application
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_app_badger: ^1.5.0
  faker: ^2.1.0
  badges: ^2.0.3
  intl: ^0.17.0
  open_mail_app: ^0.4.5
  flutter_vector_icons: ^2.0.0
  persistent_bottom_nav_bar_v2: ^4.2.5
  flutter_calendar_carousel: ^2.4.1
  flutter_riverpod: ^1.0.3+1
  dio: ^4.0.6
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  jiffy: ^5.0.0
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  shared_preferences_riverpod: ^0.2.0
  cached_network_image: ^3.2.2
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  another_flushbar: ^1.12.29
  pinput: ^2.2.16
  animated_splash_screen: ^1.3.0
  web_socket_channel: ^2.2.0
  socket_io_client: ^2.0.0
  permission_handler: ^10.0.0
  shimmer: ^2.0.0
  share_plus: ^6.3.0
  package_info_plus: ^3.0.2
  photo_view: ^0.14.0
  geolocator: ^9.0.2
  pin_code_fields: ^7.4.0
  flutter_svg: ^2.0.2
  sliding_sheet: ^0.5.2
  pin_code_text_field: ^1.8.0
  firebase_core: ^2.7.0
  onesignal_flutter: ^3.5.0
  google_maps_flutter: ^2.2.5
  url_launcher: ^6.1.10
  maps_places_autocomplete: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "EC0606"
  image: assets/chopwell_icon.svg

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          style: normal

    - family: Questrial
      fonts:
        - asset: fonts/Questrial-Regular.ttf
